"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const friendsController_1 = require("../controllers/friendsController");
const router = express_1.default.Router();
router.get("/", friendsController_1.friendsController.list);
router.get("/list", friendsController_1.friendsController.list);
router.post("/request", friendsController_1.friendsController.request);
router.post("/:userId/accept", friendsController_1.friendsController.accept);
router.post("/accept", friendsController_1.friendsController.accept);
router.post("/decline", friendsController_1.friendsController.decline);
router.delete("/:userId", friendsController_1.friendsController.remove);
exports.default = router;
