"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const invitationsController_1 = require("../controllers/invitationsController");
const router = express_1.default.Router();
router.post("/send", invitationsController_1.invitationsController.send);
router.post("/accept", invitationsController_1.invitationsController.accept);
router.post("/decline", invitationsController_1.invitationsController.decline);
router.get("/pending", invitationsController_1.invitationsController.pending);
exports.default = router;
